CREATE TABLE users (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"email" TEXT UNIQUE NOT NULL,
	"password" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE urls (
	"id" SERIAL PRIMARY KEY,
	"url" TEXT NOT NULL,
	"shortUrl" TEXT UNIQUE NOT NULL,
	"visitCount" INTEGER DEFAULT 0,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "userUrls" (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL REFERENCES "users"("id"),
	"urlId" INTEGER NOT NULL REFERENCES "urls"("id"),
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
