CREATE TABLE users (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL,
	"email" TEXT UNIQUE NOT NULL,
	"password" TEXT NOT NULL
);

CREATE TABLE urls (
	"id" SERIAL PRIMARY KEY,
	"url" TEXT NOT NULL,
	"shortUrl" TEXT UNIQUE NOT NULL,
	"visitCount" INTEGER DEFAULT 0
);

CREATE TABLE "userUrls" (
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER NOT NULL REFERENCES "users"("id"),
	"urlId" INTEGER NOT NULL REFERENCES "urls"("id")
);

CREATE TABLE sessions (
	"id" SERIAL PRIMARY KEY,
	"token" TEXT UNIQUE NOT NULL,
	"userId" INTEGER UNIQUE NOT NULL REFERENCES "users"("id")
);
